<?php

use Drupal\Core\Routing\TrustedRedirectResponse;

/**
 * Implements hook_install().
 */
function unl_cas_install() {
  \Drupal::configFactory()->getEditable('user.settings')
      ->set('register', USER_REGISTER_ADMINISTRATORS_ONLY)
      ->save(TRUE);
}

/**
 * Implements hook_user_login().
 */
function unl_cas_user_login(\Drupal\Core\Session\AccountInterface $account) {
  //Schedule a user data update for the account
  /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var \Drupal\Core\Queue\QueueInterface $queue */
  $queue = $queue_factory->get('cron_unl_user_update_user_data', true);
  $item = new \stdClass();
  $item->uid = $account->id();
  $queue->createItem($item);
}

/**
 * Implements hook_user_logout().
 */
function unl_cas_user_logout($account) {
  $cas = (new \Drupal\unl_cas\Controller\UnlCasController())->getAdapter();
  $url = $cas->getLogoutUrl(\Drupal::url('<front>', [], ['absolute' => TRUE]));
  $response = new TrustedRedirectResponse($url, 302);
  $response->addCacheableDependency((new \Drupal\Core\Cache\CacheableMetadata())->setCacheMaxAge(0));
  $response->send();
  return;
}
