<?php

use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\Core\Url;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_logout().
 */
function unl_cas_user_logout($account) {
  $unl_cas_loader = \Drupal::service('unl_cas.adapter');
  $cas = $unl_cas_loader->getAdapter();
  $url = $cas->getLogoutUrl(Url::fromRoute('<front>', [], ['absolute' => TRUE])->toString());

  $response = new TrustedRedirectResponse($url, 302);
  $response->addCacheableDependency((new \Drupal\Core\Cache\CacheableMetadata())->setCacheMaxAge(0));
  $response->send();
  return;
}
